// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterMango.Data.Entities;

namespace WaterMango.Data.Migrations
{
    [DbContext(typeof(WaterMangoContext))]
    partial class WaterMangoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WaterMango.Data.Entities.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("LastWateredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            LastWateredDate = new DateTime(2019, 12, 10, 8, 7, 26, 929, DateTimeKind.Local).AddTicks(2116),
                            Name = "Mint"
                        },
                        new
                        {
                            PlantId = 2,
                            LastWateredDate = new DateTime(2019, 12, 10, 5, 7, 26, 932, DateTimeKind.Local).AddTicks(9304),
                            Name = "Aloe"
                        },
                        new
                        {
                            PlantId = 3,
                            LastWateredDate = new DateTime(2019, 12, 9, 21, 7, 26, 932, DateTimeKind.Local).AddTicks(9376),
                            Name = "Cacti"
                        },
                        new
                        {
                            PlantId = 4,
                            Name = "Peace Lily"
                        },
                        new
                        {
                            PlantId = 5,
                            LastWateredDate = new DateTime(2019, 12, 10, 2, 7, 56, 932, DateTimeKind.Local).AddTicks(9381),
                            Name = "Catnip"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
